# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170804_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandAloneImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image-uploads')),
            ],
        ),
    ]
