# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_standaloneimageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_keywords',
            field=models.TextField(blank=True),
        ),
    ]
